#reference : https://bhavik.io/2017/12/19/consul-with-docker-swarm-mode.html
---
version: '3.3'
networks:
  overlay_net:
    external: true
services:
  cassandra:
    deploy:      
      replicas: 1 
      placement:
        constraints:
          - node.role == manager     
    entrypoint:
    - "sh"
    - "-c"
    - export CASSANDRA_SEEDS=$$(nrOfTasks=`getent hosts tasks.cassandra | wc -l` ;
      many=`getent hosts tasks.cassandra | awk '{print $$1}' | sed "/$$(hostname --ip-address)/d"
      | paste -d, -s -` ; printf '%s' $$( [ $${nrOfTasks} -gt 1 ] && echo $${many} ||
      echo "$$(hostname --ip-address)" )) ; /docker-entrypoint.sh cassandra -f
    image: cassandra:3.5
    networks:
      overlay_net:
        aliases:
          - cassandra.node
